apiVersion: v1
kind: Service
metadata:
  name: recreate-service
  labels:
    app: recreate
spec:
  selector:
    app: recreate
  type: NodePort
  ports:
  - port: 80
    nodePort: 31001
    targetPort: 80

